name: Tests & Checks

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: portfolio_test

    env:
      RAILS_ENV: test
      PGHOST: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --without development

      - name: Setup database
        run: bin/rails db:prepare

      - name: Run tests
        run: bundle exec rspec spec -f j -o tmp/rspec_results.json -f p

      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/rspec_results.json
        if: always()

  code-audits:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: rubocop
        uses: prozsolt/rubocop-github-action@master

      - name: Yarn audit
        uses: pragatheeswarans/yarn-audit-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'audit issues'
          
      - name: Brakeman
        uses: artplan1/brakeman-action@v1.2.1
        with:
          flags: "--color"

      - name: Bundler Audit
        uses: andrewmcodes/bundler-audit-action@main

